_BASE_: "det_only_v2.yaml"
CHAR_MAP:
  DIR: "TO_BE_ADDED/multiplexer/charmap/public/v2/"
DATASETS:
  AUG: False
INPUT:
  MIN_SIZE_TRAIN: (800, 1000, 1200, 1400)
  MAX_SIZE_TRAIN: 2333
MODEL:
  CHAR_MASK_ON: False
  LANGUAGE_HEAD:
    NUM_CLASSES: 8
    PREDICTOR: "V1LanguagePredictor"
  ROI_MASK_HEAD:
    MASK_BATCH_SIZE_PER_IM: 48
    PREDICTOR: "MultiSeqLangMaskRCNNC4Predictor"
    RESOLUTION_H: 64
    RESOLUTION_W: 64
  TRAIN_DETECTION_ONLY: False  # enabled e2e training
SEQUENCE:
  RESIZE_HEIGHT: 16
  RESIZE_WIDTH: 64
  NUM_SEQ_HEADS: 8
  ARABIC:
    EMBED_SIZE: 30
    HIDDEN_SIZE: 256
    NUM_CHAR: 80
  BENGALI:
    EMBED_SIZE: 30
    HIDDEN_SIZE: 256
    NUM_CHAR: 110
  CHINESE:
    EMBED_SIZE: 50
    HIDDEN_SIZE: 256
    NUM_CHAR: 3470
  DEVANAGARI:
    EMBED_SIZE: 30
    HIDDEN_SIZE: 256
    NUM_CHAR: 110
  HANGUL:
    EMBED_SIZE: 50
    HIDDEN_SIZE: 256
    NUM_CHAR: 1460
  JAPANESE:
    EMBED_SIZE: 50
    HIDDEN_SIZE: 256
    NUM_CHAR: 2210
  LATIN:
    EMBED_SIZE: 50
    HIDDEN_SIZE: 256
    NUM_CHAR: 230
  SYMBOL:
    EMBED_SIZE: 30
    HIDDEN_SIZE: 64
    NUM_CHAR: 60
SOLVER:
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 8
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 200000)
  MAX_ITER: 300000